### ISSUE TITLE
Remove little caret `^` from package.json

### ISSUE THREAD

**Issue by gacosta89** [mediamonks/seng-boilerplate#38]
Here is the article that justifies all [Software Versions are Broken](https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783#.1ye3dsyvr). 

A little intro:

"I’ll admit it. Like almost everybody in the Node community, I’m in the habit of abusing npm’s save feature:

```
npm install --save lodash
```

The problem is, it uses a neat little caret `^` to indicate that your software should automatically use non-breaking changes.
But this could be dangerous. We all know that John-David Dalton is an unstoppable robot from the future.
....
What if he’s on a secret mission to stop Skynet by slipping a time bomb into all of our code? One of these days, he’ll make a breaking change to lodash, and the next time you `npm install`, BOOM!
Your code will break. Because he won’t increment the major version number… (sneaky robot).
...."

What do you think?

**Comment by ThaNarie** [comment]
I think including and excluding the version range both have some pros and cons.

Exact matches gives you the certainty that malicious (intentional) and accidental minor/patch versions won't break your code.
This just happened with awesome-typescript-loader, and after [reporting the issue](https://github.com/s-panferov/awesome-typescript-loader/issues/200) I put in the exact match.

Range matches will put some trust into the package authors that they correctly use semver, but in turn you benefit from automatic fixes (solving bugs or improving performance).
Imagine you have an issue, spend some time finding it, and see that it was already fixed.
Granted, this only helps if you (periodically) re-install your npm modules, otherwise you won't get the updated modules.

Important note, this only helps for dependancies directly listed in your package.json, sub-dependancies are out of your hand. If you want to properly lock all installed versions, you can use the shrinkwrap feature.

**Comment by gacosta89** [comment]
> Important note, this only helps for dependencies directly listed in your package.json, sub-dependencies are out of your hand. If you want to properly lock all installed versions, you can use the shrinkwrap feature.

I vote for idempotent builds and think every one of us should fix our dependencies, but shrinkwrap looks great.

**Comment by ThaNarie** [comment]
Most of us have switched to yarn, which created a `yarn.lock` file, locking all versions.

Also, **npm@5** will `--save` by default now. Additionally, `package-lock.json` will be automatically created unless an `npm-shrinkwrap.json` exists.
So we could switch to that version as well.
